title: LMS Otomatik Ders | Otomatik yerinize derse giren yazılım
description: LMS Otomatik Ders sizin yerinize canlı derslere katılır, bu sayede sınav notunuzdan eksi almanın önüne geçersiniz.
show_downloads: true
theme: jekyll-theme-minimal
